= Issues
:sectnum:

== Maybe low-hanging fruits

- `Can't find import <module>` should be `Can't find module <module>` ?

- `:module` in the REPL brings everything in scope, including private entities.
This calls for an `:import` directive similar to the `import` in an Idris module.
Or at least a way to quickly see what's private and what's not. UPDATE: Asked
christiansen about it. The absence of this feature is a matter of priorities.

== Mutuality around an interface

Reported at https://github.com/idris-lang/Idris-dev/issues/3168

Consider this: 

[source, idris]
----
interface MyInterface a where
  bar : a -> b
  bar : ?bar_rhs
  foo : a -> b
  foo = bar
----

`foo` depends on `bar`. They both provide a default implementation
and depend on the type of the implementation.

An implementation can override `foo`, which is fine, but I don't want
`bar` to be overridden. I need it outside of the interface.

In Haskell, I would do something akin to this:

[source, idris]
----
bar : MyInterface a => a -> b
bar : ?bar_rhs

interface MyInterface a where
  foo : a -> b
  foo = bar
----

Problem is, the order is messed up because bar depends on `MyInterface`.

Symmetrically:

[source, idris]
----
interface MyInterface a where
  foo : a -> b
  foo = bar

bar : MyInterface a => a -> b
bar : ?bar_rhs
----

`foo` is trying to use the `bar` function that is not already defined. 

How such a problem would be solve?


== Interactive editing

=== Lemmata

Creating a lemma uses the whole scope to fetch arguments.
Worse, if some are already there it adds them anyway.

Maybe it should look at the intended type and simply use it to lift the hole.

Example:

[source, idris]
----
foo : a -> b -> c
foo x = ?bar
----

`bar` is of type `b -> c`. By doing a "simple lifting", we'd have:

[source, idris]
----
bar : b -> c

foo : a -> b -> c
foo x = bar
----

Going further, let's have:

[source, idris]
----
foo : a -> b -> c
foo x = ?bar x
----

Because x of type a, this could expand as:

[source, idris]
----
bar : (x : a) -> b -> c

foo : a -> b -> c
foo x = bar x
----

Instead of the current behavior

[source, idris]
----
bar : (x : a) -> a -> b -> c

foo : a -> b -> c
foo x = bar x x
----

=== Definitions in interfaces

Can't make an automatic definition of a function in an interface's `where` clause.

=== Case splits on tuples

Say I have a type `(Int, Int, Int)`. If a case split on a variable of this
type, I get `(a, b)`. I'd like to have `(a, b, c)` instead (although
tuples are implemented as nested pairs).

Tested with Atom and Vim.

=== Type of holes in where blocks

Given this snippet:

```idris
five : Int
five = two + three where
  two : Int
  two = ?two_rhs
  three : Int
  three = 3
```

This type-checks fine but I can't query the type of `?two_rhs`.

== Empty datatype causes parser error

This following snippet is a part of _Listing 6.6_ in
_Type-driven development with Idris_ (MEAP v7).

[source, idris]
----
data Schema

SchemaType : Schema -> Type
----

It raises a syntax error in `:`.

However, if the file ends with `data Schema` it compiles fine.

== Can't use multiple holes sometimes

I don't understand this:

[source, idris]
----
Can't define hole Ex6_3_8.case block in Ex6_3_8.interactiveInsert, processInput at /home/gpyh/idris-exercises/src/Ex6_3_8.idr:84:10 as i
t depends on other holes          
----

== Type synonyms don't appear in queried type signatures

If I use a type synonym (a function of type `Type`) and then query the types
in the context, only the computed type is displayed. 
This is sensible, but hardly usable. The main uses of type synonyms are giving
meaning to types and simplifying the type signatures. We can't take
advantage of this when doing interactive editing.

An example:

[source, idris]
----
Point : Type
Point = (Int, Int)

Vector : Type
Vector = (Int, Int)

vectorFromTo : Point -> Point -> Vector
vectorFromTo p1 p2 = ?hole p1 p2
----

If you query the type of `vectorFromTo` you rightfully get
`Point -> Point -> Vector`. However, the type of the hole is
`(Int, Int) -> (Int, Int) -> (Int, Int)`. Idris immediately compute the type
before displaying it. It would be nice if it was able to know not to always
evaluate functions that return a type for display purposes.
The ideal setup would be to have both displayed, so you know the _meaning_
and the _structure_ of what you're working with.


== Integral methods allow division by zero

I took a look at `Prelude.Interfaces` and implementations of the `div` method
don't handle the divide-by-zero case. How can this be prevented?
I guess it is a very complicated issue.

== No `import qualified`

When you define a lot of functions that overlap with the
imported module you wish you could do that. Is there a pattern with
`namespace` that would provide the same advantage?
